### ISSUE TITLE
Scores won’t show

### ISSUE THREAD

**Issue by athanast6** [cowboysdude/MMM-NBA#1]
Hello 
I installed your module recently and it was working. I then installed MMM-carousel to rotate between this module and MMM-NFL. I’m not sure what happened but now the scores will not show. I’m wondering if this is a compatibility issue with carousel. Any help would be appreciated. Thanks.

**Comment by cowboysdude** [comment]
I'll have to check the data

**Comment by cowboysdude** [comment]
Has a conflict with carousel..... not sure what it is.   I installed it and had a couple other people install it and it's working...... so something to do with carousel which I know nothing about :)
